package com.example.flagquiz;

public class Database {

    Integer[] flags={
            R.drawable.afghanistan,
            R.drawable.algeria,
            R.drawable.bangladesh,
            R.drawable.china,
            R.drawable.denmark,
            R.drawable.egypt,
            R.drawable.france,
            R.drawable.germany,
            R.drawable.hungary,
            R.drawable.india,
            R.drawable.nepal,
            R.drawable.japan,
            R.drawable.kuwait,
            R.drawable.lebanon,
            R.drawable.malaysia,
            R.drawable.oman,
            R.drawable.pakistan,
            R.drawable.qatar,
            R.drawable.russian_federation,
            R.drawable.saudi_arabia,
            R.drawable.turkey,
            R.drawable.uae,
            R.drawable.vietnam,
            R.drawable.yemen,
            R.drawable.zimbabwe,
            R.drawable.albania,
            R.drawable.angola,
            R.drawable.argentina,
            R.drawable.armenia,
            R.drawable.australia,
            R.drawable.austria,
            R.drawable.azerbaijan,
            R.drawable.barbados,
            R.drawable.bermuda,
            R.drawable.bhutan,
            R.drawable.brazil,
            R.drawable.brunei,
            R.drawable.cambodia,
            R.drawable.canada,
            R.drawable.chile,
            R.drawable.croatia,
            R.drawable.cuba,
            R.drawable.czech_republic,
            R.drawable.denmark,
            R.drawable.egypt,
            R.drawable.ethiopia,
            R.drawable.finland,
            R.drawable.france,
            R.drawable.georgia,
            R.drawable.gibraltar,
            R.drawable.greece,
            R.drawable.greenland,
            R.drawable.grenada,
            R.drawable.denmark,
            R.drawable.guam,
            R.drawable.hong_kong,
            R.drawable.hungary,
            R.drawable.iceland,
            R.drawable.indonesia,
            R.drawable.iran,
            R.drawable.iraq,
            R.drawable.israel,
            R.drawable.italy,
            R.drawable.jamaica,
            R.drawable.japan,
            R.drawable.jordan,
            R.drawable.kazakhstan,
            R.drawable.kuwait,
            R.drawable.kyrgyzstan,
            R.drawable.lebanon,
            R.drawable.liberia,
            R.drawable.maldives,
            R.drawable.myanmar,
            R.drawable.netherlands,
            R.drawable.niger,
            R.drawable.nigeria,
            R.drawable.north_korea,
            R.drawable.norway,
            R.drawable.panama,
            R.drawable.peru,
            R.drawable.poland,
            R.drawable.portugal,
            R.drawable.russian_federation,
            R.drawable.sierra_leone,
            R.drawable.singapore,
            R.drawable.south_africa,
            R.drawable.spain,
            R.drawable.sri_lanka,
            R.drawable.sudan,
            R.drawable.switzerland,
            R.drawable.syria,
            R.drawable.tajikistan,
            R.drawable.tanzania,
            R.drawable.thailand,
            R.drawable.tonga,
            R.drawable.tunisia,
            R.drawable.turkmenistan,
            R.drawable.uganda,
            R.drawable.ukraine,
            R.drawable.united_kingdom,
            R.drawable.uraguay,
            R.drawable.usa,
            R.drawable.uzbekistan,
            R.drawable.venezuela,
            R.drawable.yemen,
            R.drawable.belarus,
            R.drawable.soviet_union,
            R.drawable.ireland,
            R.drawable.libya




    };

    String[] answers = {
            "Afghanistan",
            "Algeria",
            "Bangladesh",
            "China",
            "Denmark",
            "Egypt",
            "France",
            "Germany",
            "Hungary",
            "India",
            "Nepal",
            "Japan",
            "Kuwait",
            "Lebanon",
            "Malaysia",
             "Oman",
            "Pakistan",
             "Qatar",
             "Russian Federation",
             "Saudi Arabia",
              "Turkey",
              "UAE",
              "Vietnam",
               "Yemen",
                "Zimbabwe",
                "Albania",
            "Angola",
            "Argentina",
            "Armenia",
            "Australia",
            "Austria",
            "Azerbaijan",
            "Barbados",
            "Bermuda",
            "Bhutan",
            "Brazil",
            "Brunei",
            "Cambodia",
            "Canada",
            "Chile",
            "Croatia",
            "Cuba",
            "Czech Republic",
            "Denmark",
            "Egypt",
            "Ethiopia",
            "Finland",
            "France",
            "Georgia",
             "Gibraltar",
            "Greece",
             "Greenland",
             "Grenada",
            "Denmark",
            "Guam",
             "Hong Kong",
            "Hungary",
            "Iceland",
            "Indonesia",
            "Iran",
            "Iraq",
            "Israel",
            "Italy",
            "Jamaica",
            "Japan",
            "Jordan",
            "Kazakhstan",
             "Kuwait",
             "Kyrgyzstan",
             "Lebanon",
              "Liberia",
              "Maldives",
               "Myanmar",
                "Netherlands",
            "Niger",
             "Nigeria",
             "North_Korea",
            "Norway",
            "Panama",
             "Peru",
            "Poland",
            "Portugal",
            "Russian Federation",
             "Sierra Leone",
             "Singapore",
            "South Africa",
            "Spain",
             "Sri Lanka",
              "Sudan",
             "Switzerland",
            "Syria",
            "Tajikistan",
             "Tanzania",
             "Thailand",
             "Tonga",
              "Tunisia",
             "Turkmenistan",
              "Uganda",
              "Ukraine",
               "United Kingdom",
                "Uraguay",
               "USA",
            "Uzbekistan",
            "Venezuela",
            "Yemen",
             "Belarus",
             "Soviet Union",
            "Ireland",
             "Libya"


    };
}
